# Generated by Django 3.1.5 on 2021-02-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210205_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdata',
            old_name='year3',
            new_name='year',
        ),
    ]
