# Generated by Django 3.1.7 on 2021-04-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210218_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='indicator_type',
        ),
        migrations.AddField(
            model_name='indicator',
            name='percentile',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='indicator',
            name='value',
            field=models.DecimalField(decimal_places=99, default=0, max_digits=999),
        ),
        migrations.AddField(
            model_name='indicator',
            name='variable',
            field=models.CharField(default='', max_length=256),
        ),
    ]
