# Generated by Django 3.1.7 on 2021-04-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210411_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='data',
        ),
    ]
