# Generated by Django 3.1.7 on 2021-05-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_indicator_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorPercentile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='percentile',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='variable',
        ),
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.indicatortype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatortype',
            name='description',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='indicatortype',
            name='percentiles',
            field=models.ManyToManyField(to='api.IndicatorPercentile'),
        ),
    ]
