# Generated by Django 3.1.7 on 2021-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_indicatortype_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatortype',
            name='description',
            field=models.TextField(default='', unique=True),
        ),
    ]
