# Generated by Django 3.1.7 on 2021-05-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210520_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='percentile',
            field=models.TextField(default='', max_length=30, unique=True),
        ),
    ]
