# Generated by Django 3.1.7 on 2021-05-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210520_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='percentile',
        ),
    ]
