# Generated by Django 3.1.7 on 2021-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_indicator_percentile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='percentile',
            field=models.CharField(default='', max_length=30),
        ),
    ]
