# Generated by Django 3.1.7 on 2021-05-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210520_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorpercentile',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
